import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { SupportedLanguage } from '../types';

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string, defaultText?: string) => string;
}

export const LANGUAGE_LABELS: Record<SupportedLanguage, { label: string; nativeName: string; flag: string }> = {
  en: { label: 'English', nativeName: 'English', flag: '🇬🇧' },
  hi: { label: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  mr: { label: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  gu: { label: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  ta: { label: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' }
};

const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Branding & Header
    system_title: 'Legal Metrology Online Verification System',
    tagline: 'Measure Right, Build Trust',
    dept_name: 'Department of Consumer Affairs, Government of India',
    govt_of_india: 'Govt of India',
    welcome_back: 'Welcome back',
    manage_sub: 'Manage your instruments, applications and certificates with ease.',

    // Navigation & Menus
    dashboard: 'Dashboard',
    my_instruments: 'My Instruments',
    instruments: 'Instruments',
    instrument_registry: 'Instrument Registry',
    applications: 'Applications',
    certificates: 'Certificates',
    issued_certificates: 'Issued Certificates',
    verified_badge: 'Verified Badge',
    scan_qr: 'Scan QR',
    scan_qr_verify: 'Scan QR & Verify',
    scan_scale_qr: 'Scan Instrument / Cert QR',
    public_verify: 'Public Verify',
    public_cert_check: 'Public Certificate Check',
    alerts: 'Alerts',
    user_manual: 'User Manual',
    gatc_guidelines: 'GATC Guidelines',
    legal_metrology_rules: 'Legal Metrology Rules',
    settings: 'Settings',
    support: 'Support',
    logout: 'Sign Out / Switch User',
    sign_in: 'Sign In',
    field_map: 'Field Map',
    field_route_map: 'Field Route Map',
    enforcement: 'Enforcement & Raids',
    citizen_reports: 'Citizen Reports',
    citizen_report: 'Report Issue / Tampering',
    near_me: 'Find Verified Businesses',
    sla: 'SLA Dashboard',
    rule_engine: 'Rule Engine',
    reports: 'Reports',
    audit: 'Audit Trail',
    gatc_dashboard: 'GATC Dashboard',
    settings_preferences: 'Settings & Preferences',
    search_placeholder: 'Search instruments, applications, certificates, officers (Ctrl + K)...',

    // Dashboard Stats & Cards
    registered_instruments: 'Registered Instruments',
    applications_in_progress: 'Applications in Progress',
    active_certificates: 'Active Certificates',
    valid_certificates: 'Valid Certificates',
    expiring_soon: 'Expiring ≤ 90 Days',
    due_soon: 'Due Soon',
    expired: 'Expired',
    active: 'Active',
    total_applications: 'Total Applications',
    applications_in_scrutiny: 'Applications in Scrutiny',
    verification_in_progress: 'Verification in Progress',
    awaiting_allocation: 'Awaiting Allocation',
    instruments_at_drift_risk: 'Instruments at Drift Risk',
    open_citizen_reports: 'Open Citizen Reports',
    sla_breaches: 'SLA Breaches',
    quick_actions: 'Quick Actions',
    attention_needed: 'Attention Needed',
    recent_applications: 'Recent Applications',
    view_all: 'View All',
    attention_expiring_desc: '1 certificate(s) expiring within 90 days.',
    weighbridge_expiring_sub: 'Weighbridge (WB-Pitless-60T) due on Oct 14, 2026.',

    // Actions & Buttons
    register_instrument: 'Register Instrument',
    new_application: 'New Verification Application',
    apply_verification: 'Apply Verification',
    apply_reverification: 'Apply Re-Verification',
    issue_certificate: 'e-Sign & Issue Certificate',
    scan_nameplate: 'Scan Nameplate',
    save: 'Save',
    save_settings: 'Save Settings',
    cancel: 'Cancel',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    download_pdf: 'Download PDF Placard',
    share_whatsapp: 'Share to WhatsApp',
    view: 'View',
    edit: 'Edit',
    delete: 'Delete',
    filter: 'Filter',
    export: 'Export',
    print: 'Print',
    verify: 'Verify',
    get_started: 'Get Started',
    start_inspection: 'Start Inspection',
    generate_seizure: 'Generate Seizure Notice',
    allocate: 'Allocate',
    change_password: 'Change Password',
    enable_2fa: 'Enable 2-Factor Authentication',
    discard_changes: 'Discard Changes',

    // Table & Form Headers
    app_no: 'App No.',
    instrument: 'Instrument',
    instrument_type: 'Instrument Type',
    category: 'Category',
    manufacturer: 'Manufacturer',
    model_no: 'Model No.',
    serial_no: 'Serial No.',
    accuracy_class: 'Accuracy Class',
    max_capacity: 'Max Capacity',
    min_capacity: 'Min Capacity',
    type: 'Type',
    status: 'Status',
    filed_on: 'Filed On',
    action: 'Action',
    actions: 'Actions',
    open: 'Open',
    done: 'Done',
    certificate_no: 'Certificate No.',
    issue_date: 'Issue Date',
    expiry_date: 'Expiry Date',
    valid_until: 'Valid Until',
    officer: 'Officer',
    business_name: 'Business Name',
    location: 'Location',
    district: 'District',
    address: 'Address',
    fee: 'Statutory Fee',
    fee_paid: 'Fee Paid',
    payment_ref: 'Payment Ref',
    jurisdiction: 'Jurisdiction',

    // Statuses
    submitted: 'Submitted',
    in_scrutiny: 'In Scrutiny',
    approved: 'Approved',
    allocated: 'Allocated',
    scheduled: 'Scheduled',
    in_verification: 'In Verification',
    certificate_generated: 'Certificate Generated',
    rejected: 'Rejected',
    registered: 'Registered',
    verified: 'Verified',
    under_inspection: 'Under Inspection',
    flagged: 'Flagged',
    passed: 'Passed',
    failed: 'Failed',
    valid: 'Valid',
    calibration_required: 'Calibration Required',

    // Roles
    business_owner: 'Business Owner',
    lmo_officer: 'Legal Metrology Officer (LMO)',
    gatc_center: 'GATC Calibration Lab Center',
    admin: 'Department Controller / Admin',
    citizen: 'Public Citizen',

    // Settings
    profile: 'Profile',
    full_name: 'Full Name',
    email_address: 'Email Address',
    mobile_number: 'Mobile Number',
    notification_preferences: 'Notification Preferences',
    email_notifications: 'Email Notifications',
    in_app_notifications: 'In-App Notifications',
    language_region: 'Language & Region',
    interface_language: 'Interface Language',
    date_format: 'Date Format',
    security: 'Security',
    settings_saved: 'Settings saved successfully.',
    expiry_notice_desc: 'Certificate Expiry Advance Notice',

    // Verification & Hardware
    geo_lock_ok: 'GPS Verified on Site',
    mpe_pass: 'PASS',
    mpe_fail: 'FAIL',
    load_test: 'Digital Load Test',
    standard_weights: 'Standard Weights',
    observed_reading: 'Observed Reading',
    error_margin: 'Error Margin',
    max_permissible_error: 'Max Permissible Error (MPE)',
    security_seal: 'Security Seal Number',
    stamp_id: 'Stamp ID',
    aadhaar_esign: 'Aadhaar e-Sign Verification',
    digital_cert: 'Digital Certificate of Verification'
  },

  hi: {
    // Branding & Header
    system_title: 'विधिक मापविज्ञान ऑनलाइन सत्यापन प्रणाली',
    tagline: 'सही माप, पक्का विश्वास',
    dept_name: 'उपभोक्ता मामले विभाग, भारत सरकार',
    govt_of_india: 'भारत सरकार',
    welcome_back: 'वापसी पर स्वागत है',
    manage_sub: 'अपने उपकरणों, आवेदनों और प्रमाणपत्रों का आसानी से प्रबंधन करें।',

    // Navigation & Menus
    dashboard: 'डैशबोर्ड',
    my_instruments: 'मेरे उपकरण',
    instruments: 'उपकरण',
    instrument_registry: 'उपकरण रजिस्ट्री',
    applications: 'आवेदन',
    certificates: 'प्रमाणपत्र',
    issued_certificates: 'जारी प्रमाणपत्र',
    verified_badge: 'सत्यापित बैज',
    scan_qr: 'क्यूआर स्कैन',
    scan_qr_verify: 'क्यूआर स्कैन व सत्यापन',
    scan_scale_qr: 'उपकरण / प्रमाणपत्र क्यूआर स्कैन',
    public_verify: 'सार्वजनिक सत्यापन',
    public_cert_check: 'प्रमाणपत्र जांच',
    alerts: 'अलर्ट',
    user_manual: 'उपयोगकर्ता निर्देशिका',
    gatc_guidelines: 'GATC दिशानिर्देश',
    legal_metrology_rules: 'विधिक मापविज्ञान नियम',
    settings: 'सेटिंग्स',
    support: 'सहायता',
    logout: 'साइन आउट / उपयोगकर्ता बदलें',
    sign_in: 'साइन इन करें',
    field_map: 'फील्ड मैप',
    field_route_map: 'फील्ड रूट मैप',
    enforcement: 'प्रवर्तन एवं छापे',
    citizen_reports: 'नागरिक शिकायतें',
    citizen_report: 'गड़बड़ी / छेड़छाड़ की रिपोर्ट',
    near_me: 'निकटतम सत्यापित दुकानें',
    sla: 'SLA डैशबोर्ड',
    rule_engine: 'नियम इंजन',
    reports: 'रिपोर्ट्स',
    audit: 'ऑडिट ट्रेल',
    gatc_dashboard: 'GATC लैब डैशबोर्ड',
    settings_preferences: 'सेटिंग्स और प्राथमिकताएं',
    search_placeholder: 'उपकरण, आवेदन, प्रमाणपत्र, अधिकारी खोजें (Ctrl + K)...',

    // Dashboard Stats & Cards
    registered_instruments: 'पंजीकृत उपकरण',
    applications_in_progress: 'प्रगतिरत आवेदन',
    active_certificates: 'सक्रिय प्रमाणपत्र',
    valid_certificates: 'वैध प्रमाणपत्र',
    expiring_soon: '९० दिनों में समाप्त',
    due_soon: 'शीघ्र देय',
    expired: 'समाप्त (Expired)',
    active: 'सक्रिय',
    total_applications: 'कुल आवेदन',
    applications_in_scrutiny: 'जांच अधीन आवेदन',
    verification_in_progress: 'सत्यापन प्रगति पर',
    awaiting_allocation: 'आवंटन की प्रतीक्षा में',
    instruments_at_drift_risk: 'विचलन जोखिम उपकरण',
    open_citizen_reports: 'लंबित नागरिक शिकायतें',
    sla_breaches: 'SLA उल्लंघन',
    quick_actions: 'त्वरित कार्रवाइयां',
    attention_needed: 'ध्यान देने योग्य',
    recent_applications: 'हालिया आवेदन',
    view_all: 'सभी देखें',
    attention_expiring_desc: '1 प्रमाणपत्र 90 दिनों के भीतर समाप्त हो रहा है।',
    weighbridge_expiring_sub: 'वेब्रिज (WB-Pitless-60T) 14 अक्टूबर, 2026 को देय है।',

    // Actions & Buttons
    register_instrument: 'नया उपकरण पंजीकृत करें',
    new_application: 'सत्यापन आवेदन करें',
    apply_verification: 'सत्यापन के लिए आवेदन करें',
    apply_reverification: 'पुनः सत्यापन आवेदन',
    issue_certificate: 'ई-हस्ताक्षर व प्रमाणपत्र जारी करें',
    scan_nameplate: 'नेमप्लेट स्कैन करें',
    save: 'सहेजें',
    save_settings: 'सेटिंग्स सहेजें',
    cancel: 'रद्द करें',
    close: 'बंद करें',
    back: 'पीछे',
    next: 'आगे',
    submit: 'जमा करें',
    download_pdf: 'पीडीएफ प्लेकार्ड डाउनलोड करें',
    share_whatsapp: 'व्हाट्सएप पर साझा करें',
    view: 'देखें',
    edit: 'संशोधित करें',
    delete: 'हटाएं',
    filter: 'फ़िल्टर',
    export: 'निर्यात करें',
    print: 'प्रिंट करें',
    verify: 'सत्यापित करें',
    get_started: 'प्रारंभ करें',
    start_inspection: 'निरीक्षण शुरू करें',
    generate_seizure: 'जब्ती नोटिस बनाएं',
    allocate: 'आवंटित करें',
    change_password: 'पासवर्ड बदलें',
    enable_2fa: '2-कारक प्रमाणीकरण सक्षम करें',
    discard_changes: 'परिवर्तन छोड़ें',

    // Table & Form Headers
    app_no: 'आवेदन सं.',
    instrument: 'उपकरण',
    instrument_type: 'उपकरण का प्रकार',
    category: 'श्रेणी',
    manufacturer: 'निर्माता',
    model_no: 'मॉडल सं.',
    serial_no: 'सीरियल सं.',
    accuracy_class: 'सटीकता वर्ग',
    max_capacity: 'अधिकतम क्षमता',
    min_capacity: 'न्यूनतम क्षमता',
    type: 'प्रकार',
    status: 'स्थिति',
    filed_on: 'दर्ज तिथि',
    action: 'कार्रवाई',
    actions: 'कार्रवाइयां',
    open: 'खुला',
    done: 'पूर्ण',
    certificate_no: 'प्रमाणपत्र सं.',
    issue_date: 'जारी तिथि',
    expiry_date: 'समाप्ति तिथि',
    valid_until: 'वैधता तिथि',
    officer: 'अधिकारी',
    business_name: 'व्यवसाय का नाम',
    location: 'स्थान',
    district: 'जिला',
    address: 'पता',
    fee: 'वैधानिक शुल्क',
    fee_paid: 'शुल्क भुगतान',
    payment_ref: 'भुगतान संदर्भ',
    jurisdiction: 'अधिकार क्षेत्र',

    // Statuses
    submitted: 'जमा किया गया',
    in_scrutiny: 'जांच जारी',
    approved: 'स्वीकृत',
    allocated: 'आवंटित',
    scheduled: 'निर्धारित',
    in_verification: 'सत्यापन में',
    certificate_generated: 'प्रमाणपत्र जनरेटेड',
    rejected: 'अस्वीकृत',
    registered: 'पंजीकृत',
    verified: 'सत्यापित',
    under_inspection: 'निरीक्षणाधीन',
    flagged: 'चिह्नित',
    passed: 'उत्तीर्ण (PASS)',
    failed: 'अनुत्तीर्ण (FAIL)',
    valid: 'वैध',
    calibration_required: 'अंशांकन आवश्यक',

    // Roles
    business_owner: 'व्यापारी / प्रतिष्ठान मालिक',
    lmo_officer: 'विधिक मापविज्ञान अधिकारी (LMO)',
    gatc_center: 'GATC प्रयोगशाला केंद्र',
    admin: 'राज्य नियंत्रक / एडमिन',
    citizen: 'नागरिक / उपभोक्ता',

    // Settings
    profile: 'प्रोफ़ाइल',
    full_name: 'पूरा नाम',
    email_address: 'ईमेल पता',
    mobile_number: 'मोबाइल नंबर',
    notification_preferences: 'अधिसूचना प्राथमिकताएं',
    email_notifications: 'ईमेल सूचनाएं',
    in_app_notifications: 'ऐप सूचनाएं',
    language_region: 'भाषा और क्षेत्र',
    interface_language: 'इंटरफ़ेस भाषा',
    date_format: 'तिथि प्रारूप',
    security: 'सुरक्षा',
    settings_saved: 'सेटिंग्स सफलतापूर्वक सहेजी गईं।',
    expiry_notice_desc: 'प्रमाणपत्र समाप्ति अग्रिम सूचना',

    // Verification & Hardware
    geo_lock_ok: 'स्थल पर जीपीएस सत्यापित',
    mpe_pass: 'पास (PASS)',
    mpe_fail: 'फेल (FAIL)',
    load_test: 'डिजिटल भार परीक्षण',
    standard_weights: 'मानक भार (Standard Weights)',
    observed_reading: 'अवलोकित माप',
    error_margin: 'त्रुटि सीमा',
    max_permissible_error: 'अधिकतम स्वीकार्य त्रुटि (MPE)',
    security_seal: 'सुरक्षा सील संख्या',
    stamp_id: 'मुहर आईडी (Stamp ID)',
    aadhaar_esign: 'आधार ई-हस्ताक्षर सत्यापन',
    digital_cert: 'डिजिटल सत्यापन प्रमाणपत्र'
  },

  mr: {
    // Branding & Header
    system_title: 'वैधानिक मापनशास्त्र ऑनलाइन पडताळणी प्रणाली',
    tagline: 'अचूक मापन, दृढ विश्वास',
    dept_name: 'ग्राहक व्यवहार विभाग, भारत सरकार',
    govt_of_india: 'भारत सरकार',
    welcome_back: 'आपले स्वागत आहे',
    manage_sub: 'आपली उपकरणे, अर्ज आणि प्रमाणपत्रांचे सुलभ व्यवस्थापन करा.',

    // Navigation & Menus
    dashboard: 'डॅशबोर्ड',
    my_instruments: 'माझी उपकरणे',
    instruments: 'उपकरणे',
    instrument_registry: 'उपकरण नोंदवही',
    applications: 'अर्ज',
    certificates: 'प्रमाणपत्रे',
    issued_certificates: 'जारी केलेली प्रमाणपत्रे',
    verified_badge: 'पडताळणीकृत बॅज',
    scan_qr: 'क्यूआर स्कॅन',
    scan_qr_verify: 'क्यूआर स्कॅन व पडताळणी',
    scan_scale_qr: 'उपकरण / प्रमाणपत्र क्यूआर स्कॅन',
    public_verify: 'सार्वजनिक पडताळणी',
    public_cert_check: 'प्रमाणपत्र तपासणी',
    alerts: 'सूचना',
    user_manual: 'वापरकर्ता मार्गदर्शक',
    gatc_guidelines: 'GATC मार्गदर्शक तत्त्वे',
    legal_metrology_rules: 'वैधानिक मापनशास्त्र नियम',
    settings: 'सेटिंग्ज',
    support: 'मदत व सहाय्य',
    logout: 'साइन आउट / वापरकर्ता बदला',
    sign_in: 'साइन इन करा',
    field_map: 'फील्ड नकाशा',
    field_route_map: 'फील्ड मार्ग नकाशा',
    enforcement: 'अंमलबजावणी व छापे',
    citizen_reports: 'नागरिक तक्रारी',
    citizen_report: 'गैरव्यवहार / छेडछाड तक्रार',
    near_me: 'जवळपासची पडताळणीकृत दुकाने',
    sla: 'SLA डॅशबोर्ड',
    rule_engine: 'नियम इंजिन',
    reports: 'अहवाल',
    audit: 'ऑडिट नोंदी',
    gatc_dashboard: 'GATC लॅब डॅशबोर्ड',
    settings_preferences: 'सेटिंग्ज आणि पसंती',
    search_placeholder: 'उपकरणे, अर्ज, प्रमाणपत्रे, अधिकारी शोधा (Ctrl + K)...',

    // Dashboard Stats & Cards
    registered_instruments: 'नोंदणीकृत उपकरणे',
    applications_in_progress: 'प्रगतीपथावरील अर्ज',
    active_certificates: 'सक्रिय प्रमाणपत्रे',
    valid_certificates: 'वैध प्रमाणपत्रे',
    expiring_soon: '९० दिवसांत मुदत संपणारे',
    due_soon: 'लवकरच देय',
    expired: 'मुदत संपलेले',
    active: 'सक्रिय',
    total_applications: 'एकूण अर्ज',
    applications_in_scrutiny: 'तपासणी अंतर्गत अर्ज',
    verification_in_progress: 'पडताळणी सुरू',
    awaiting_allocation: 'वाटपाच्या प्रतीक्षेत',
    instruments_at_drift_risk: 'विचलन जोखीम उपकरणे',
    open_citizen_reports: 'प्रलंबित नागरिक तक्रारी',
    sla_breaches: 'SLA उल्लंघन',
    quick_actions: 'द्रुत कृती',
    attention_needed: 'लक्ष देण्याची गरज',
    recent_applications: 'अलीकडील अर्ज',
    view_all: 'सर्व पहा',
    attention_expiring_desc: '1 प्रमाणपत्राची मुदत 90 दिवसांत संपत आहे.',
    weighbridge_expiring_sub: 'वेब्रिज (WB-Pitless-60T) देय तारीख १४ ऑक्टोबर २०२६.',

    // Actions & Buttons
    register_instrument: 'उपकरण नोंदणी करा',
    new_application: 'नवीन पडताळणी अर्ज',
    apply_verification: 'पडताळणीसाठी अर्ज करा',
    apply_reverification: 'पुनःपडताळणी अर्ज करा',
    issue_certificate: 'ई-स्वाक्षरी व प्रमाणपत्र द्या',
    scan_nameplate: 'नेमप्लेट स्कॅन करा',
    save: 'जतन करा',
    save_settings: 'सेटिंग्ज जतन करा',
    cancel: 'रद्द करा',
    close: 'बंद करा',
    back: 'मागे',
    next: 'पुढे',
    submit: 'सादर करा',
    download_pdf: 'पीडीएफ डाउनलोड करा',
    share_whatsapp: 'व्हॉट्सॲपवर शेअर करा',
    view: 'पहा',
    edit: 'संपादित करा',
    delete: 'हटवा',
    filter: 'फिल्टर',
    export: 'निर्यात करा',
    print: 'प्रिंट करा',
    verify: 'पडताळणी करा',
    get_started: 'सुरू करा',
    start_inspection: 'तपासणी सुरू करा',
    generate_seizure: 'जप्ती नोटीस तयार करा',
    allocate: 'वाटप करा',
    change_password: 'पासवर्ड बदला',
    enable_2fa: '२-घटक प्रमाणीकरण सुरू करा',
    discard_changes: 'बदल रद्द करा',

    // Table & Form Headers
    app_no: 'अर्ज क्र.',
    instrument: 'उपकरण',
    instrument_type: 'उपकरणाचा प्रकार',
    category: 'वर्गवारी',
    manufacturer: 'उत्पादक',
    model_no: 'मॉडेल क्र.',
    serial_no: 'अनुक्रमांक',
    accuracy_class: 'अचूकता श्रेणी',
    max_capacity: 'कमाल क्षमता',
    min_capacity: 'किमान क्षमता',
    type: 'प्रकार',
    status: 'स्थिती',
    filed_on: 'अर्ज दिनांक',
    action: 'कृती',
    actions: 'कृती',
    open: 'उघडा',
    done: 'पूर्ण',
    certificate_no: 'प्रमाणपत्र क्र.',
    issue_date: 'जारी दिनांक',
    expiry_date: 'मुदत समाप्ती दिनांक',
    valid_until: 'वैधता दिनांक',
    officer: 'अधिकारी',
    business_name: 'व्यवसायाचे नाव',
    location: 'स्थान',
    district: 'जिल्हा',
    address: 'पत्ता',
    fee: 'वैधानिक शुल्क',
    fee_paid: 'शुल्क भरले',
    payment_ref: 'पेमेंट संदर्भ',
    jurisdiction: 'अधिकारक्षेत्र',

    // Statuses
    submitted: 'सादर केले',
    in_scrutiny: 'छाननी सुरू',
    approved: 'मंजूर',
    allocated: 'वाटप केले',
    scheduled: 'नियोजित',
    in_verification: 'पडताळणीत',
    certificate_generated: 'प्रमाणपत्र तयार झाले',
    rejected: 'नाकारले',
    registered: 'नोंदणीकृत',
    verified: 'पडताळणीकृत',
    under_inspection: 'तपासणी सुरू',
    flagged: 'चिन्हांकित',
    passed: 'उत्तीर्ण (PASS)',
    failed: 'अनुत्तीर्ण (FAIL)',
    valid: 'वैध',
    calibration_required: 'कॅलिब्रेशन आवश्यक',

    // Roles
    business_owner: 'व्यावसायिक / मालक',
    lmo_officer: 'वैधानिक मापनशास्त्र अधिकारी (LMO)',
    gatc_center: 'GATC प्रयोगशाळा केंद्र',
    admin: 'राज्य नियंत्रक / प्रशासक',
    citizen: 'नागरिक / ग्राहक',

    // Settings
    profile: 'प्रोफाइल',
    full_name: 'पूर्ण नाव',
    email_address: 'ईमेल पत्ता',
    mobile_number: 'मोबाईल नंबर',
    notification_preferences: 'सूचना पसंती',
    email_notifications: 'ईमेल सूचना',
    in_app_notifications: 'ॲपमधील सूचना',
    language_region: 'भाषा आणि प्रदेश',
    interface_language: 'इंटरफेस भाषा',
    date_format: 'दिनांक स्वरूप',
    security: 'सुरक्षा',
    settings_saved: 'सेटिंग्ज यशस्वीरित्या जतन केल्या.',
    expiry_notice_desc: 'प्रमाणपत्र समाप्ती पूर्वसूचना',

    // Verification & Hardware
    geo_lock_ok: 'घटनास्थळी जीपीएस पडताळणी झाली',
    mpe_pass: 'पास (PASS)',
    mpe_fail: 'नापास (FAIL)',
    load_test: 'डिजिटल भार चाचणी',
    standard_weights: 'प्रमाणित वजने',
    observed_reading: 'नोंदवलेले वाचन',
    error_margin: 'त्रुटी मर्यादा',
    max_permissible_error: 'कमाल स्वीकार्य त्रुटी (MPE)',
    security_seal: 'सुरक्षा सील क्रमांक',
    stamp_id: 'स्टॅम्प आयडी',
    aadhaar_esign: 'आधार ई-स्वाक्षरी पडताळणी',
    digital_cert: 'डिजिटल पडताळणी प्रमाणपत्र'
  },

  gu: {
    // Branding & Header
    system_title: 'કાનૂની માપવિજ્ઞાન ઓનલાઈન ચકાસણી સિસ્ટમ',
    tagline: 'સાચું માપ, પાકો વિશ્વાસ',
    dept_name: 'ગ્રાહક બાબતોનો વિભાગ, ભારત સરકાર',
    govt_of_india: 'ભારત સરકાર',
    welcome_back: 'આપનું સ્વાગત છે',
    manage_sub: 'તમારા સાધનો, અરજીઓ અને પ્રમાણપત્રોનું સરળતાથી સંચાલન કરો.',

    // Navigation & Menus
    dashboard: 'ડેશબોર્ડ',
    my_instruments: 'મારા ઉપકરણો',
    instruments: 'ઉપકરણો',
    instrument_registry: 'સાધન રજિસ્ટ્રી',
    applications: 'અરજીઓ',
    certificates: 'પ્રમાણપત્રો',
    issued_certificates: 'ઇશ્યૂ કરેલ પ્રમાણપત્રો',
    verified_badge: 'ચકાસાયેલ બેજ',
    scan_qr: 'QR સ્કેન',
    scan_qr_verify: 'QR સ્કેન અને ચકાસણી',
    scan_scale_qr: 'સાધન / પ્રમાણપત્ર QR સ્કેન',
    public_verify: 'જાહેર ચકાસણી',
    public_cert_check: 'પ્રમાણપત્ર તપાસ',
    alerts: 'સૂચનાઓ',
    user_manual: 'વપરાશકર્તા માર્ગદર્શિકા',
    gatc_guidelines: 'GATC માર્ગદર્શિકા',
    legal_metrology_rules: 'કાનૂની માપવિજ્ઞાન નિયમો',
    settings: 'સેટિંગ્સ',
    support: 'સહાયતા',
    logout: 'સાઇન આઉટ / વપરાશકર્તા બદલો',
    sign_in: 'સાઇન ઇન કરો',
    field_map: 'ફીલ્ડ નકશો',
    field_route_map: 'ફીલ્ડ રૂટ નકશો',
    enforcement: 'અમલીકરણ અને દરોડા',
    citizen_reports: 'નાગરિક ફરિયાદો',
    citizen_report: 'છેડછાડની ફરિયાદ નોંધાવો',
    near_me: 'નજીકની પ્રમાણિત દુકાનો',
    sla: 'SLA ડેશબોર્ડ',
    rule_engine: 'નિયમ એન્જિન',
    reports: 'અહેવાલો',
    audit: 'ઓડિટ લોગ',
    gatc_dashboard: 'GATC લેબ ડેશબોર્ડ',
    settings_preferences: 'સેટિંગ્સ અને પસંદગીઓ',
    search_placeholder: 'સાધનો, અરજીઓ, પ્રમાણપત્રો, અધિકારીઓ શોધો (Ctrl + K)...',

    // Dashboard Stats & Cards
    registered_instruments: 'નોંધાયેલ ઉપકરણો',
    applications_in_progress: 'પ્રગતિ હેઠળની અરજીઓ',
    active_certificates: 'સક્રિય પ્રમાણપત્રો',
    valid_certificates: 'માન્ય પ્રમાણપત્રો',
    expiring_soon: '૯૦ દિવસમાં સમાપ્ત',
    due_soon: 'ટૂંક સમયમાં બાકી',
    expired: 'સમાપ્ત થયેલ',
    active: 'સક્રિય',
    total_applications: 'કુલ અરજીઓ',
    applications_in_scrutiny: 'ચકાસણી હેઠળની અરજીઓ',
    verification_in_progress: 'ચકાસણી પ્રગતિમાં',
    awaiting_allocation: 'ફાળવણીની રાહમાં',
    instruments_at_drift_risk: 'વિચલન જોખમી સાધનો',
    open_citizen_reports: 'બાકી નાગરિક ફરિયાદો',
    sla_breaches: 'SLA ઉલ્લંઘન',
    quick_actions: 'ઝડપી ક્રિયાઓ',
    attention_needed: 'ધ્યાન આપવાની જરૂર',
    recent_applications: 'તાજેતરની અરજીઓ',
    view_all: 'બધા જુઓ',
    attention_expiring_desc: '1 પ્રમાણપત્ર 90 દિવસમાં સમાપ્ત થઈ રહ્યું છે.',
    weighbridge_expiring_sub: 'વેઇબ્રિજ (WB-Pitless-60T) નિયત તારીખ 14 ઑક્ટોબર 2026.',

    // Actions & Buttons
    register_instrument: 'સાધન નોંધણી કરો',
    new_application: 'નવી ચકાસણી અરજી',
    apply_verification: 'ચકાસણી માટે અરજી કરો',
    apply_reverification: 'પુનઃચકાસણી અરજી',
    issue_certificate: 'ઈ-સહી અને પ્રમાણપત્ર જારી કરો',
    scan_nameplate: 'નેમપ્લેટ સ્કેન કરો',
    save: 'સાચવો',
    save_settings: 'સેટિંગ્સ સાચવો',
    cancel: 'રદ કરો',
    close: 'બંધ કરો',
    back: 'પાછા',
    next: 'આગળ',
    submit: 'સબમિટ કરો',
    download_pdf: 'પીડીએફ ડાઉનલોડ કરો',
    share_whatsapp: 'વોટ્સએપ પર શેર કરો',
    view: 'જુઓ',
    edit: 'ફેરફાર કરો',
    delete: 'કાઢી નાખો',
    filter: 'ફિલ્ટર',
    export: 'નિકાસ કરો',
    print: 'પ્રિન્ટ કરો',
    verify: 'ચકાસો',
    get_started: 'શરૂ કરો',
    start_inspection: 'તપાસ શરૂ કરો',
    generate_seizure: 'જપ્તી નોટિસ બનાવો',
    allocate: 'ફાળવો',
    change_password: 'પાસવર્ડ બદલો',
    enable_2fa: '૨-પરિબળ પ્રમાણીકરણ સક્ષમ કરો',
    discard_changes: 'ફેરફારો રદ કરો',

    // Table & Form Headers
    app_no: 'અરજી નં.',
    instrument: 'ઉપકરણ',
    instrument_type: 'સાધન પ્રકાર',
    category: 'શ્રેણી',
    manufacturer: 'ઉત્પાદક',
    model_no: 'મોડેલ નં.',
    serial_no: 'અનુક્રમ નંબર',
    accuracy_class: 'ચોકસાઈ વર્ગ',
    max_capacity: 'મહત્તમ ક્ષમતા',
    min_capacity: 'ન્યૂનતમ ક્ષમતા',
    type: 'પ્રકાર',
    status: 'સ્થિતિ',
    filed_on: 'અરજી તારીખ',
    action: 'ક્રિયા',
    actions: 'ક્રિયાઓ',
    open: 'ખોલો',
    done: 'પૂર્ણ',
    certificate_no: 'પ્રમાણપત્ર નં.',
    issue_date: 'ઇશ્યૂ તારીખ',
    expiry_date: 'સમાપ્તિ તારીખ',
    valid_until: 'માન્યતા તારીખ',
    officer: 'અધિકારી',
    business_name: 'વેપારનું નામ',
    location: 'સ્થળ',
    district: 'જિલ્લો',
    address: 'સરનામું',
    fee: 'કાનૂની ફી',
    fee_paid: 'ફી ચૂકવી',
    payment_ref: 'ચુકવણી સંદર્ભ',
    jurisdiction: 'અધિકાર ક્ષેત્ર',

    // Statuses
    submitted: 'સબમિટ થયેલ',
    in_scrutiny: 'તપાસ હેઠળ',
    approved: 'મંજૂર',
    allocated: 'ફાળવેલ',
    scheduled: 'નિયત થયેલ',
    in_verification: 'ચકાસણીમાં',
    certificate_generated: 'પ્રમાણપત્ર જનરેટ થયું',
    rejected: 'અસ્વીકાર્ય',
    registered: 'નોંધાયેલ',
    verified: 'ચકાસાયેલ',
    under_inspection: 'તપાસ હેઠળ',
    flagged: 'ચિહ્નિત',
    passed: 'પાસ (PASS)',
    failed: 'ફેલ (FAIL)',
    valid: 'માન્ય',
    calibration_required: 'કેલિબ્રેશન જરૂરી',

    // Roles
    business_owner: 'વેપારી / માલિક',
    lmo_officer: 'કાનૂની માપવિજ્ઞાન અધિકારી (LMO)',
    gatc_center: 'GATC લેબોરેટરી સેન્ટર',
    admin: 'રાજ્ય નિયામક / એડમિન',
    citizen: 'નાગરિક / ગ્રાહક',

    // Settings
    profile: 'પ્રોફાઇલ',
    full_name: 'પૂરું નામ',
    email_address: 'ઇમેઇલ સરનામું',
    mobile_number: 'મોબાઇલ નંબર',
    notification_preferences: 'સૂચના પસંદગીઓ',
    email_notifications: 'ઇમેઇલ સૂચનાઓ',
    in_app_notifications: 'એપ્લિકેશન સૂચનાઓ',
    language_region: 'ભાષા અને પ્રદેશ',
    interface_language: 'ઇન્ટરફેસ ભાષા',
    date_format: 'તારીખ ફોર્મેટ',
    security: 'સુરક્ષા',
    settings_saved: 'સેટિંગ્સ સફળતાપૂર્વક સાચવવામાં આવી.',
    expiry_notice_desc: 'પ્રમાણપત્ર સમાપ્તિ પૂર્વ સૂચના',

    // Verification & Hardware
    geo_lock_ok: 'સ્થળ પર GPS ચકાસાયેલ',
    mpe_pass: 'પાસ (PASS)',
    mpe_fail: 'ફેલ (FAIL)',
    load_test: 'ડિજિટલ લોડ ટેસ્ટ',
    standard_weights: 'પ્રમાણભૂત વજન',
    observed_reading: 'નોંધાયેલ માપ',
    error_margin: 'ભૂલ મર્યાદા',
    max_permissible_error: 'મહત્તમ સ્વીકાર્ય ભૂલ (MPE)',
    security_seal: 'સિક્યોરિટી સીલ નંબર',
    stamp_id: 'સ્ટેમ્પ આઈડી',
    aadhaar_esign: 'આધાર ઈ-સહી ચકાસણી',
    digital_cert: 'ડિજિટલ ચકાસણી પ્રમાણપત્ર'
  },

  ta: {
    // Branding & Header
    system_title: 'சட்ட அளவியல் ஆன்லைன் சரிபார்ப்பு அமைப்பு',
    tagline: 'சரியான அளவீடு, அசைக்க முடியாத நம்பிக்கை',
    dept_name: 'நுகர்வோர் விவகாரத்துறை, இந்திய அரசு',
    govt_of_india: 'இந்திய அரசு',
    welcome_back: 'மீண்டும் நல்வரவு',
    manage_sub: 'உங்கள் எடைக்கருவிகள், விண்ணப்பங்கள் மற்றும் சான்றிதழ்களை எளிதாக நிர்வகிக்கவும்.',

    // Navigation & Menus
    dashboard: 'டாஷ்போர்டு',
    my_instruments: 'எனது கருவிகள்',
    instruments: 'கருவிகள்',
    instrument_registry: 'கருவி பதிவேடு',
    applications: 'விண்ணப்பங்கள்',
    certificates: 'சான்றிதழ்கள்',
    issued_certificates: 'வழங்கப்பட்ட சான்றிதழ்கள்',
    verified_badge: 'சரிபார்க்கப்பட்ட முத்திரை',
    scan_qr: 'QR ஸ்கேன்',
    scan_qr_verify: 'QR ஸ்கேன் & சரிபார்ப்பு',
    scan_scale_qr: 'கருவி / சான்றிதழ் QR ஸ்கேன்',
    public_verify: 'பொது சரிபார்ப்பு',
    public_cert_check: 'சான்றிதழ் சரிபார்ப்பு',
    alerts: 'எச்சரிக்கைகள்',
    user_manual: 'பயனர் கையேடு',
    gatc_guidelines: 'GATC வழிகாட்டுதல்கள்',
    legal_metrology_rules: 'சட்ட அளவியல் விதிகள்',
    settings: 'அமைப்புகள்',
    support: 'ஆதரவு & உதவி',
    logout: 'வெளியேறு / பயனரை மாற்றுக',
    sign_in: 'உள்நுழைக',
    field_map: 'கள வரைபடம்',
    field_route_map: 'கள ஆய்வு பாதை வரைபடம்',
    enforcement: 'அமலாக்கம் & சோதனைகள்',
    citizen_reports: 'பொதுமக்கள் புகார்கள்',
    citizen_report: 'எடை மோசடி புகார் செய்க',
    near_me: 'அருகிலுள்ள சரிபார்க்கப்பட்ட கடைகள்',
    sla: 'SLA டாஷ்போர்டு',
    rule_engine: 'விதி பொறிமுறை',
    reports: 'அறிக்கைகள்',
    audit: 'தணிக்கை பதிவு',
    gatc_dashboard: 'GATC ஆய்வக டாஷ்போர்டு',
    settings_preferences: 'அமைப்புகள் மற்றும் விருப்பங்கள்',
    search_placeholder: 'கருவிகள், விண்ணப்பங்கள், சான்றிதழ்களைத் தேடுக (Ctrl + K)...',

    // Dashboard Stats & Cards
    registered_instruments: 'பதிவுசெய்த கருவிகள்',
    applications_in_progress: 'செயல்பாட்டில் உள்ள விண்ணப்பங்கள்',
    active_certificates: 'செயலில் உள்ள சான்றிதழ்கள்',
    valid_certificates: 'செல்லுபடியாகும் சான்றிதழ்கள்',
    expiring_soon: '90 நாட்களில் காலாவதி',
    due_soon: 'விரைவில் காலாவதி',
    expired: 'காலாவதியானது',
    active: 'செயலில் உள்ளது',
    total_applications: 'மொத்த விண்ணப்பங்கள்',
    applications_in_scrutiny: 'பரிசீலனையில் உள்ள விண்ணப்பங்கள்',
    verification_in_progress: 'சரிபார்ப்பு நடைபெறுகிறது',
    awaiting_allocation: 'ஒதுக்கீட்டுக்குக் காத்திருக்கிறது',
    instruments_at_drift_risk: 'விலகல் அபாயமுள்ள கருவிகள்',
    open_citizen_reports: 'நிலுவையில் உள்ள புகார்கள்',
    sla_breaches: 'SLA விதிமீறல்கள்',
    quick_actions: 'விரைவுச் செயல்கள்',
    attention_needed: 'கவனம் தேவை',
    recent_applications: 'சமீபத்திய விண்ணப்பங்கள்',
    view_all: 'அனைத்தையும் காண்க',
    attention_expiring_desc: '1 சான்றிதழ் 90 நாட்களுக்குள் காலாவதியாகிறது.',
    weighbridge_expiring_sub: 'எடைப்பாலம் (WB-Pitless-60T) அக்டோபர் 14, 2026 அன்று காலாவதி.',

    // Actions & Buttons
    register_instrument: 'கருவியை பதிவு செய்க',
    new_application: 'புதிய சரிபார்ப்பு விண்ணப்பம்',
    apply_verification: 'சரிபார்ப்புக்கு விண்ணப்பிக்கவும்',
    apply_reverification: 'மறு சரிபார்ப்பு விண்ணப்பம்',
    issue_certificate: 'இ-கையொப்பம் & சான்றிதழ் வழங்குக',
    scan_nameplate: 'பெயர் பலகையை ஸ்கேன் செய்க',
    save: 'சேமிக்க',
    save_settings: 'அமைப்புகளைச் சேமிக்க',
    cancel: 'ரத்து செய்',
    close: 'மூடுக',
    back: 'பின்செல்',
    next: 'அடுத்து',
    submit: 'சமர்ப்பிக்க',
    download_pdf: 'PDF பதிவிறக்கம்',
    share_whatsapp: 'வாட்ஸ்அப்பில் பகிர்க',
    view: 'காண்க',
    edit: 'திருத்துக',
    delete: 'நீக்குக',
    filter: 'வடிகட்டு',
    export: 'ஏற்றுமதி செய்க',
    print: 'அச்சிடுக',
    verify: 'சரிபார்க்க',
    get_started: 'தொடங்குக',
    start_inspection: 'ஆய்வைத் தொடங்குக',
    generate_seizure: 'பறிமுதல் குறிப்பு உருவாக்குக',
    allocate: 'ஒதுக்கீடு செய்க',
    change_password: 'கடவுச்சொல்லை மாற்றுக',
    enable_2fa: '2-காரணி அங்கீகாரத்தை இயக்குக',
    discard_changes: 'மாற்றங்களை நிராகரி',

    // Table & Form Headers
    app_no: 'விண்ணப்ப எண்',
    instrument: 'கருவி',
    instrument_type: 'கருவி வகை',
    category: 'பிரிவு',
    manufacturer: 'உற்பத்தியாளர்',
    model_no: 'மாதிரி எண்',
    serial_no: 'வரிசை எண்',
    accuracy_class: 'துல்லிய வகுப்பு',
    max_capacity: 'அதிகபட்ச கொள்ளளவு',
    min_capacity: 'குறைந்தபட்ச கொள்ளளவு',
    type: 'வகை',
    status: 'நிலை',
    filed_on: 'தாக்கல் செய்த தேதி',
    action: 'செயல்',
    actions: 'செயல்கள்',
    open: 'திறக்க',
    done: 'முடிந்தது',
    certificate_no: 'சான்றிதழ் எண்',
    issue_date: 'வழங்கப்பட்ட தேதி',
    expiry_date: 'காலாவதி தேதி',
    valid_until: 'செல்லுபடியாகும் காலம்',
    officer: 'அதிகாரி',
    business_name: 'வணிகத்தின் பெயர்',
    location: 'இடம்',
    district: 'மாவட்டம்',
    address: 'முகவரி',
    fee: 'சட்டப்படியான கட்டணம்',
    fee_paid: 'கட்டணம் செலுத்தப்பட்டது',
    payment_ref: 'பரிவர்த்தனை எண்',
    jurisdiction: 'அதிகார வரம்பு',

    // Statuses
    submitted: 'சமர்ப்பிக்கப்பட்டது',
    in_scrutiny: 'ஆய்வில் உள்ளது',
    approved: 'அங்கீகரிக்கப்பட்டது',
    allocated: 'ஒதுக்கப்பட்டது',
    scheduled: 'திட்டமிடப்பட்டது',
    in_verification: 'சரிபார்ப்பில் உள்ளது',
    certificate_generated: 'சான்றிதழ் உருவாக்கப்பட்டது',
    rejected: 'நிராகரிக்கப்பட்டது',
    registered: 'பதிவு செய்யப்பட்டது',
    verified: 'சரிபார்க்கப்பட்டது',
    under_inspection: 'ஆய்வில் உள்ளது',
    flagged: 'குறியிடப்பட்டது',
    passed: 'தேர்ச்சி (PASS)',
    failed: 'தோல்வி (FAIL)',
    valid: 'செல்லுபடியாகும்',
    calibration_required: 'அளவீடு திருத்தம் தேவை',

    // Roles
    business_owner: 'வணிக உரிமையாளர்',
    lmo_officer: 'சட்ட அளவியல் ஆய்வாளர் (LMO)',
    gatc_center: 'GATC அளவீட்டு ஆய்வகம்',
    admin: 'மாநில கட்டுப்பாட்டாளர் / நிர்வாகி',
    citizen: 'பொது நுகர்வோர்',

    // Settings
    profile: 'சுயவிவரம்',
    full_name: 'முழுப் பெயர்',
    email_address: 'மின்னஞ்சல் முகவரி',
    mobile_number: 'மொபைல் எண்',
    notification_preferences: 'அறிவிப்பு விருப்பங்கள்',
    email_notifications: 'மின்னஞ்சல் அறிவிப்புகள்',
    in_app_notifications: 'செயலி அறிவிப்புகள்',
    language_region: 'மொழி மற்றும் பிராந்தியம்',
    interface_language: 'இடைமுக மொழி',
    date_format: 'தேதி வடிவம்',
    security: 'பாதுகாப்பு',
    settings_saved: 'அமைப்புகள் வெற்றிகரமாகச் சேமிக்கப்பட்டன.',
    expiry_notice_desc: 'சான்றிதழ் காலாவதி முன்னறிவிப்பு',

    // Verification & Hardware
    geo_lock_ok: 'களத்தில் GPS சரிபார்க்கப்பட்டது',
    mpe_pass: 'தேர்ச்சி (PASS)',
    mpe_fail: 'தோல்வி (FAIL)',
    load_test: 'டிஜிட்டல் எடை சுமை சோதனை',
    standard_weights: 'நிலையான எடைக் கற்கள்',
    observed_reading: 'அளவிடப்பட்ட வாசிப்பு',
    error_margin: 'பிழை வரம்பு',
    max_permissible_error: 'அனுமதிக்கப்பட்ட அதிகபட்ச பிழை (MPE)',
    security_seal: 'பாதுகாப்பு முத்திரை எண்',
    stamp_id: 'முத்திரை அடையாள எண் (Stamp ID)',
    aadhaar_esign: 'ஆதார் இ-கையொப்ப சரிபார்ப்பு',
    digital_cert: 'டிஜிட்டல் சரிபார்ப்பு சான்றிதழ்'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    const saved = localStorage.getItem('merix_selected_lang') as SupportedLanguage;
    if (saved && translations[saved]) {
      return saved;
    }
    return 'en';
  });

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    localStorage.setItem('merix_selected_lang', lang);
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string, defaultText?: string): string => {
    if (!key) return defaultText || '';

    // 1. Direct exact key match
    const langDict = translations[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }

    // 2. Normalized snake_case key match
    const normalizedKey = key
      .toLowerCase()
      .trim()
      .replace(/[^\w\s]/g, '')
      .replace(/\s+/g, '_');

    if (langDict && langDict[normalizedKey]) {
      return langDict[normalizedKey];
    }

    // 3. Reverse lookup if an English value was passed as key
    const enDict = translations.en;
    for (const [k, v] of Object.entries(enDict)) {
      if (
        v.toLowerCase() === key.toLowerCase().trim() ||
        k.toLowerCase() === normalizedKey
      ) {
        if (langDict && langDict[k]) {
          return langDict[k];
        }
      }
    }

    // 4. English fallback
    if (enDict[key]) return enDict[key];
    if (enDict[normalizedKey]) return enDict[normalizedKey];

    // 5. Default text or key
    return defaultText || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
